export const baseIp = 'http://192.168.0.112:6666/'

export const GET_USERS_STARTED = 'GET_USERS_STARTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const SET_DEFAULT_USER_STATE = 'SET_DEFAULT_USER_STATE';

export const GET_USER_STARTED = 'GET_USER_STARTED';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const ADD_USER_STARTED = 'ADD_USER_STARTED';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const CHECK_USER_STARTED = 'CHECK_USER_STARTED';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAIL = 'CHECK_USER_FAIL';

export const UPDATE_USER_PHOTO_SUCCESS = 'UPDATE_USER_PHOTO_SUCCESS';
export const UPDATE_USER_PHOTO_FAIL = 'UPDATE_USER_PHOTO_FAIL';
export const UPDATE_USER_PHOTO_STARTED = 'UPDATE_USER_PHOTO_STARTED';

export const GET_NOTES_STARTED = 'GET_NOTES_STARTED';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAIL = 'GET_NOTES_FAIL';

export const SET_DEFAULT_NOTES_STATE = 'SET_DEFAULT_NOTES_STATE';

export const ADD_NOTE_STARTED = 'ADD_NOTE_STARTED';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';

export const DELETE_NOTE_STARTED = 'DELETE_NOTE_STARTED';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL';

export const FIND_NOTE_STARTED = 'FIND_NOTE_STARTED';
export const FIND_NOTE_SUCCESS = 'FIND_NOTE_SUCCESS';
export const FIND_NOTE_FAIL = 'FIND_NOTE_FAIL';

export const UPDATE_NOTE_TEXT_STARTED = 'UPDATE_NOTE_TEXT_STARTED';
export const UPDATE_NOTE_TEXT_SUCCESS = 'UPDATE_NOTE_TEXT_SUCCESS';
export const UPDATE_NOTE_TEXT_FAIL = 'UPDATE_NOTE_TEXT_FAIL';

export const UPDATE_NOTE_PROPRETIES_STARTED = 'UPDATE_NOTE_PROPRETIES_STARTED';
export const UPDATE_NOTE_PROPRETIES_SUCCESS = 'UPDATE_NOTE_PROPRETIES_SUCCESS';
export const UPDATE_NOTE_PROPRETIES_FAIL = 'UPDATE_NOTE_PROPRETIES_FAIL';

export const UPDATE_NOTE_LIST_STARTED = 'UPDATE_NOTE_LIST_STARTED';
export const UPDATE_NOTE_LIST_SUCCESS = 'UPDATE_NOTE_LIST_SUCCESS';
export const UPDATE_NOTE_LIST_FAIL = 'UPDATE_NOTE_LIST_FAIL';

export const SET_DEFAULT_NOTE_STATE = 'SET_DEFAULT_NOTE_STATE';

